<?php
/* include/language/gl_es.lang.php */
if(!defined('sugarEntry'))define('sugarEntry', true);
/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Public License Version
 * 1.1.3 ("License"); You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at http://www.sugarcrm.com/SPL
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied.  See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * All copies of the Covered Code must include on each user interface screen:
 *    (i) the "Powered by SugarCRM" logo and
 *    (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 *
 * The Original Code is: SugarCRM Open Source
 * Contributor: Lampada CRM 
 * David O'Keefe
 * info@lampadacrm.com.br
 *	
 * The Initial Developer of the Original Code is SugarCRM, Inc.
 * Portions created by SugarCRM are Copyright (C) 2004-2006 SugarCRM, Inc.;
 * All Rights Reserved.
 ********************************************************************************/
$app_list_strings=array(
  'language_pack_name' => 'Galician',
  'moduleList' => array (
    'Home' => 'Inicio',
    'Dashboard' => 'Panel de control',
    'Contacts' => 'Contactos',
    'Accounts' => 'Contas',
    'Opportunities' => 'Oportunidades',
    'Cases' => 'Casos',
    'Notes' => 'Notas',
    'Calls' => 'Chamadas',
    'Emails' => 'Correos',
    'Meetings' => 'Reunións',
    'Tasks' => 'Tarefas',
    'Calendar' => 'Calendario',
    'Leads' => 'Contactos iniciais',
    'Activities' => 'Actividades',
    'Bugs' => 'Seguimento de incidencias',
    'Feeds' => 'RSS',
    'iFrames' => 'O meu portal',
    'TimePeriods' => 'Períodos temporais',
    'Project' => 'Proxectos',
    'ProjectTask' => 'Tarefas de proxectos',
    'Campaigns' => 'Campañas',
    'Documents' => 'Documentos',
    'Sync' => 'Sincronizar',
    'Users' => 'Usuarios',
    'Releases' => 'Versións',
    'Prospects' => 'Obxectivos',
    'Queues' => 'Filas',
    'EmailMarketing' => 'Mercadotecnia por correo',
    'EmailTemplates' => 'Modelos de correo',
    'ProspectLists' => 'Listas de obxectivos',
    'SavedSearch' => 'Buscas gardadas',
  ),
  'moduleListSingular' => array (
    'Home' => 'Inicio',
    'Dashboard' => 'Panel de control',
    'Contacts' => 'Contacto',
    'Accounts' => 'Conta',
    'Opportunities' => 'Oportunidade',
    'Cases' => 'Caso',
    'Notes' => 'Nota',
    'Calls' => 'Chamada',
    'Emails' => 'Correo electrónico',
    'Meetings' => 'Reunión',
    'Tasks' => 'Tarefa',
    'Calendar' => 'Calendario',
    'Leads' => 'Contacto inicial',
    'Activities' => 'Actividade',
    'Bugs' => 'Seguimento de incidencias',
    'Feeds' => 'RSS',
    'iFrames' => 'O meu portal',
    'TimePeriods' => 'Período temporal',
    'Project' => 'Proxectos',
    'ProjectTask' => 'Tarefa de proxecto',
    'Campaigns' => 'Campañas',
    'Documents' => 'Documentos',
    'Sync' => 'Sincronizar',
    'Users' => 'Usuario',
  ),
  'checkbox_dom' => array (
    '0' => '',
    '1' => 'Si',
    '2' => 'Non',
  ),
  'account_type_dom' => array (
    '0' => '',
    'Analyst' => 'Analista',
    'Competitor' => 'Competidor',
    'Customer' => 'Cliente',
    'Integrator' => 'Integrador',
    'Investor' => 'Inversor',
    'Partner' => 'Socio',
    'Press' => 'Prensa',
    'Prospect' => 'Cliente potencial',
    'Reseller' => 'Revendedor',
    'Other' => 'Outro',
  ),
  'industry_dom' => array (
    '0' => '',
    'Apparel' => 'Téxtil',
    'Banking' => 'Banca',
    'Biotechnology' => 'Biotecnoloxía',
    'Chemicals' => 'Química',
    'Communications' => 'Comunicacións',
    'Construction' => 'Construción',
    'Consulting' => 'Consultora',
    'Education' => 'Educación',
    'Electronics' => 'Electrónica',
    'Energy' => 'Enerxía',
    'Engineering' => 'Enxeñaría',
    'Entertainment' => 'Entretemento',
    'Environmental' => 'Medio ambiente',
    'Finance' => 'Finanzas',
    'Government' => 'Goberno',
    'Healthcare' => 'Saúde',
    'Hospitality' => 'Hostalería',
    'Insurance' => 'Seguros',
    'Machinery' => 'Maquinaria',
    'Manufacturing' => 'Manufactureira',
    'Media' => 'Medios de comunicación',
    'Not For Profit' => 'Sen ánimo de lucro',
    'Recreation' => 'Ocio',
    'Retail' => 'Retallista',
    'Shipping' => 'Transporte marítimo',
    'Technology' => 'Tecnoloxía',
    'Telecommunications' => 'Telecomunicacións',
    'Transportation' => 'Transportes',
    'Utilities' => 'Servizos públicos',
    'Other' => 'Outro',
  ),
  'source_default_key' => '',
  'lead_source_dom' => array (
    '0' => '',
    'Cold Call' => 'Venda directa',
    'Existing Customer' => 'Cliente existente',
    'Self Generated' => 'Xerado automaticamente',
    'Employee' => 'Empregado',
    'Partner' => 'Socio',
    'Public Relations' => 'Relacións públicas',
    'Direct Mail' => 'Correo directo',
    'Conference' => 'Conferencia',
    'Trade Show' => 'Exposición',
    'Web Site' => 'Sitio Web',
    'Word of mouth' => 'Recomendación',
    'Email' => 'Correo electrónico',
    'Campaign' => 'Campaña',
    'Other' => 'Outro',
  ),
  'opportunity_type_dom' => array (
    '0' => '',
    'Existing Business' => 'Negocio existente',
    'New Business' => 'Novo negocio',
  ),
  'roi_type_dom' => array (
    'Revenue' => 'Ingresos',
    'Investment' => 'Investimento',
    'Expected_Revenue' => 'Ingresos esperados',
    'Budget' => 'Orzamento',
  ),
  'opportunity_relationship_type_default_key' => 'Responsable primario',
  'opportunity_relationship_type_dom' => array (
    '0' => '',
    'Primary Decision Maker' => 'Responsable primario',
    'Business Decision Maker' => 'Responsable de negocios',
    'Business Evaluator' => 'Avaliador de negocios',
    'Technical Decision Maker' => 'Responsable técnico',
    'Technical Evaluator' => 'Avaliador técnico',
    'Executive Sponsor' => 'Promotor executivo',
    'Influencer' => 'Influente',
    'Other' => 'Outro',
  ),
  'case_relationship_type_default_key' => 'Contacto principal',
  'case_relationship_type_dom' => array (
    '0' => '',
    'Primary Contact' => 'Contacto principal',
    'Alternate Contact' => 'Contacto alternativo',
  ),
  'payment_terms' => array (
    '0' => '',
    'Net 15' => 'Neto 15',
    'Net 30' => 'Neto 30',
  ),
  'sales_stage_default_key' => 'Prospección',
  'sales_stage_dom' => array (
    'Prospecting' => 'Prospección',
    'Qualification' => 'Cualificación',
    'Needs Analysis' => 'Precisa análise',
    'Value Proposition' => 'Proposta de valor',
    'Id. Decision Makers' => 'Id. responsables',
    'Perception Analysis' => 'Análise de percepción',
    'Proposal/Price Quote' => 'Proposta/Orzamento',
    'Negotiation/Review' => 'Negociación/Revisión',
    'Closed Won' => 'Pechada como gañada',
    'Closed Lost' => 'Pechada como perdida',
  ),
  'sales_probability_dom' => array (
    'Prospecting' => '10',
    'Qualification' => '20',
    'Needs Analysis' => '25',
    'Value Proposition' => '30',
    'Id. Decision Makers' => '40',
    'Perception Analysis' => '50',
    'Proposal/Price Quote' => '65',
    'Negotiation/Review' => '80',
    'Closed Won' => '100',
    'Closed Lost' => '0',
  ),
  'activity_dom' => array (
    'Call' => 'Chamada',
    'Meeting' => 'Reunión',
    'Task' => 'Tarefa',
    'Email' => 'Correo',
    'Note' => 'Nota',
  ),
  'salutation_dom' => array (
    '0' => '',
    'Mr.' => 'Sr.',
    'Ms.' => 'Sra.',
    'Mrs.' => 'Sra.',
    'Dr.' => 'Dr./Dra.',
    'Prof.' => 'Prof./Profa.',
  ),
  'reminder_max_time' => '3600',
  'reminder_time_options' => array (
    '60' => '1 minuto antes',
    '300' => '5 minutos antes',
    '600' => '10 minutos antes',
    '900' => '15 minutos antes',
    '1800' => '30 minutos antes',
    '3600' => '1 hora antes',
  ),
  'task_priority_default' => 'Media',
  'task_priority_dom' => array (
    'High' => 'Alta',
    'Medium' => 'Media',
    'Low' => 'Baixa',
  ),
  'task_status_default' => 'Non iniciada',
  'task_status_dom' => array (
    'Not Started' => 'Non iniciada',
    'In Progress' => 'En progreso',
    'Completed' => 'Terminada',
    'Pending Input' => 'Entrada pendente',
    'Deferred' => 'Adiada',
  ),
  'meeting_status_default' => 'Planificada',
  'meeting_status_dom' => array (
    'Planned' => 'Planificada',
    'Held' => 'Celebrada',
    'Not Held' => 'Non celebrada',
  ),
  'call_status_default' => 'Planificada',
  'call_status_dom' => array (
    'Planned' => 'Planificada',
    'Held' => 'Celebrada',
    'Not Held' => 'Non celebrada',
  ),
  'call_direction_default' => 'Saínte',
  'call_direction_dom' => array (
    'Inbound' => 'Entrante',
    'Outbound' => 'Saínte',
  ),
  'lead_status_dom' => array (
    '0' => '',
    'New' => 'Nova',
    'Assigned' => 'Asignada',
    'In Process' => 'En proceso',
    'Converted' => 'Convertida',
    'Recycled' => 'Reciclada',
    'Dead' => 'Morta',
  ),
  'lead_status_noblank_dom' => array (
    'New' => 'Nova',
    'Assigned' => 'Asignada',
    'In Process' => 'En proceso',
    'Converted' => 'Convertida',
    'Recycled' => 'Reciclada',
    'Dead' => 'Morta',
  ),
  'case_status_default_key' => 'Novo',
  'case_status_dom' => array (
    'New' => 'Novo',
    'Assigned' => 'Asignado',
    'Closed' => 'Pechado',
    'Pending Input' => 'Entrada pendente',
    'Rejected' => 'Rexeitado',
    'Duplicate' => 'Duplicado',
  ),
  'case_priority_default_key' => 'P2',
  'case_priority_dom' => array (
    'P1' => 'Alta',
    'P2' => 'Media',
    'P3' => 'Baixa',
  ),
  'user_status_dom' => array (
    'Active' => 'Activo',
    'Inactive' => 'Inactivo',
  ),
  'employee_status_dom' => array (
    'Active' => 'Activo',
    'Terminated' => 'Despedido',
    'Leave of Absence' => 'Excedencia',
  ),
  'messenger_type_dom' => array (
    '0' => '',
    'MSN' => 'MSN',
    'Yahoo!' => 'Yahoo!',
    'AOL' => 'AOL',
  ),
  'project_task_priority_options' => array (
    'High' => 'Alta',
    'Medium' => 'Media',
    'Low' => 'Baixa',
  ),
  'project_task_status_options' => array (
    'Not Started' => 'Non iniciada',
    'In Progress' => 'En progreso',
    'Completed' => 'Terminada',
    'Pending Input' => 'Entrada pendente',
    'Deferred' => 'Adiada',
  ),
  'project_task_utilization_options' => array (
    '0' => 'ningunha',
    '25' => '25',
    '50' => '50',
    '75' => '75',
    '100' => '100',
  ),
  'record_type_default_key' => 'Contas',
  'record_type_display' => array (
    '0' => '',
    'Accounts' => 'Conta',
    'Opportunities' => 'Oportunidade',
    'Cases' => 'Caso',
    'Leads' => 'Contacto inicial',
    'Contacts' => 'Contactos',
    'Bugs' => 'Incidencia',
    'Project' => 'Proxecto',
    'ProjectTask' => 'Tarefa de proxecto',
    'Tasks' => 'Tarefa',
    'Prospects' => 'Cliente potencial',
  ),
  'record_type_display_notes' => array (
    'Accounts' => 'Conta',
    'Contacts' => 'Contacto',
    'Opportunities' => 'Oportunidade',
    'Cases' => 'Caso',
    'Leads' => 'Contacto inicial',
    'Bugs' => 'Incidencia',
    'Emails' => 'Correo electrónico',
    'Project' => 'Proxecto',
    'ProjectTask' => 'Tarefa de proxecto',
    'Meetings' => 'Reunión',
    'Calls' => 'Chamada',
  ),
  'quote_type_dom' => array (
    'Quotes' => 'Orzamento',
    'Orders' => 'Pedido',
  ),
  'default_quote_stage_key' => 'Borrador',
  'quote_stage_dom' => array (
    'Draft' => 'Borrador',
    'Negotiation' => 'Negociación',
    'Delivered' => 'Entregado',
    'On Hold' => 'En espera',
    'Confirmed' => 'Confirmado',
    'Closed Accepted' => 'Pechado como aceptado',
    'Closed Lost' => 'Pechado como perdido',
    'Closed Dead' => 'Pechado como morto',
  ),
  'default_order_stage_key' => 'Pendente',
  'order_stage_dom' => array (
    'Pending' => 'Pendente',
    'Confirmed' => 'Confirmado',
    'On Hold' => 'En espera',
    'Shipped' => 'Enviado',
    'Cancelled' => 'Cancelado',
  ),
  'quote_relationship_type_default_key' => 'Responsable primario',
  'quote_relationship_type_dom' => array (
    '0' => '',
    'Primary Decision Maker' => 'Responsable primario',
    'Business Decision Maker' => 'Responsable de negocios',
    'Business Evaluator' => 'Avaliador de negocios',
    'Technical Decision Maker' => 'Responsable técnico',
    'Technical Evaluator' => 'Avaliador técnico',
    'Executive Sponsor' => 'Promotor executivo',
    'Influencer' => 'Influente',
    'Other' => 'Outro',
  ),
  'layouts_dom' => array (
    'Standard' => 'Proposta',
    'Invoice' => 'Factura',
    'Terms' => 'Prazos de pagamento',
  ),
  'bug_priority_default_key' => 'Media',
  'bug_priority_dom' => array (
    'Urgent' => 'Urxente',
    'High' => 'Alta',
    'Medium' => 'Media',
    'Low' => 'Baixa',
  ),
  'bug_resolution_default_key' => '',
  'bug_resolution_dom' => array (
    '0' => '',
    'Accepted' => 'Aceptada',
    'Duplicate' => 'Duplicada',
    'Fixed' => 'Arranxada',
    'Out of Date' => 'Caducada',
    'Invalid' => 'Non válida',
    'Later' => 'Máis tarde',
  ),
  'bug_status_default_key' => 'Nova',
  'bug_status_dom' => array (
    'New' => 'Nova',
    'Assigned' => 'Asignada',
    'Closed' => 'Pechada',
    'Pending' => 'Pendente',
    'Rejected' => 'Rexeitada',
  ),
  'bug_type_default_key' => 'Incidencia',
  'bug_type_dom' => array (
    'Defect' => 'Defecto',
    'Feature' => 'Característica',
  ),
  'source_dom' => array (
    '0' => '',
    'Internal' => 'Interno',
    'Forum' => 'Foro',
    'Web' => 'Web',
    'InboundEmail' => 'Correo',
  ),
  'product_category_default_key' => '',
  'product_category_dom' => array (
    '0' => '',
    'Accounts' => 'Contas',
    'Activities' => 'Actividades',
    'Bug Tracker' => 'Seguimento de incidencias',
    'Calendar' => 'Calendario',
    'Calls' => 'Chamadas',
    'Campaigns' => 'Campañas',
    'Cases' => 'Casos',
    'Contacts' => 'Contactos',
    'Currencies' => 'Moedas',
    'Dashboard' => 'Panel de control',
    'Documents' => 'Documentos',
    'Emails' => 'Correos',
    'Feeds' => 'Fontes RSS',
    'Forecasts' => 'Prognósticos',
    'Help' => 'Axuda',
    'Home' => 'Inicio',
    'Leads' => 'Contactos iniciais',
    'Meetings' => 'Reunións',
    'Notes' => 'Notas',
    'Opportunities' => 'Oportunidades',
    'Outlook Plugin' => 'Plugin do Outlook',
    'Product Catalog' => 'Catálogo de produtos',
    'Products' => 'Produtos',
    'Projects' => 'Proxectos',
    'Quotes' => 'Orzamentos',
    'Releases' => 'Publicacións',
    'RSS' => 'RSS',
    'Studio' => 'Estudio',
    'Upgrade' => 'Actualización',
    'Users' => 'Usuarios',
  ),
  'campaign_status_dom' => array (
    '0' => '',
    'Planning' => 'Planificación',
    'Active' => 'Activa',
    'Inactive' => 'Inactiva',
    'Complete' => 'Terminada',
    'In Queue' => 'Na fila',
    'Sending' => 'Enviando',
  ),
  'campaign_type_dom' => array (
    '0' => '',
    'Telesales' => 'Televendas',
    'Mail' => 'Correo',
    'Email' => 'Correo electrónico',
    'Print' => 'Imprenta',
    'Web' => 'Web',
    'Radio' => 'Radio',
    'Television' => 'Televisión',
    'NewsLetter' => 'Boletín de noticias',
  ),
  'newsletter_frequency_dom' => array (
    '0' => '',
    'Weekly' => 'Semanalmente',
    'Monthly' => 'Mensualmente',
    'Quarterly' => 'Trimestralmente',
    'Annually' => 'Anualmente',
  ),
  'notifymail_sendtype' => array (
    'sendmail' => 'sendmail',
    'SMTP' => 'SMTP',
  ),
  'dom_timezones' => array (
    '-12' => '(GMT - 12) Liña internacional de cambio de data Oeste',
    '-11' => '(GMT - 11) Illa Midway, Samoa',
    '-10' => '(GMT - 10) Hawai',
    '-9' => '(GMT - 9) Alaska',
    '-8' => '(GMT - 8) San Francisco',
    '-7' => '(GMT - 7) Phoenix',
    '-6' => '(GMT - 6) Saskatchewan',
    '-5' => '(GMT - 5) Nova York',
    '-4' => '(GMT - 4) Santiago',
    '-3' => '(GMT - 3) Buenos Aires',
    '-2' => '(GMT - 2) Atlántico medio',
    '-1' => '(GMT - 1) Azores',
    '0' => '(GMT)',
    '1' => '(GMT + 1) Madrid',
    '2' => '(GMT + 2) Atenas',
    '3' => '(GMT + 3) Moscova',
    '4' => '(GMT + 4) Kabul',
    '5' => '(GMT + 5) Ekaterinburg',
    '6' => '(GMT + 6) Astana',
    '7' => '(GMT + 7) Bangkok',
    '8' => '(GMT + 8) Perth',
    '9' => '(GMT + 9) Seúl',
    '10' => '(GMT + 10) Brisbane',
    '11' => '(GMT + 11) Illas Salomón',
    '12' => '(GMT + 12) Auckland',
  ),
  'dom_cal_month_long' => array (
    '0' => '',
    '1' => 'Xaneiro',
    '2' => 'Febreiro',
    '3' => 'Marzo',
    '4' => 'Abril',
    '5' => 'Maio',
    '6' => 'Xuño',
    '7' => 'Xullo',
    '8' => 'Agosto',
    '9' => 'Setembro',
    '10' => 'Outubro',
    '11' => 'Novembro',
    '12' => 'Decembro',
  ),
  'dom_meridiem_lowercase' => array (
    'am' => 'am',
    'pm' => 'pm',
  ),
  'dom_meridiem_uppercase' => array (
    'AM' => 'AM',
    'PM' => 'PM',
  ),
  'dom_report_types' => array (
    'tabular' => 'Filas e columnas',
    'summary' => 'Resumo',
    'detailed_summary' => 'Resumo detallado',
  ),
  'dom_email_types' => array (
    'out' => 'Enviado',
    'archived' => 'Arquivado',
    'draft' => 'Borrador',
    'inbound' => 'Entrante',
    'campaign' => 'Campaña',
  ),
  'dom_email_status' => array (
    'archived' => 'Arquivado',
    'closed' => 'Pechado',
    'draft' => 'En borrador',
    'read' => 'Lido',
    'replied' => 'Respondido',
    'sent' => 'Enviado',
    'send_error' => 'Erro no envío',
    'unread' => 'Non lido',
  ),
  'dom_email_server_type' => array (
    '0' => '',
    'imap' => 'IMAP',
    'pop3' => 'POP3',
  ),
  'dom_mailbox_type' => array (
    'pick' => 'Crear [calquera]',
    'bug' => 'Crear incidencia',
    'support' => 'Crear caso',
    'contact' => 'Crear contacto',
    'sales' => 'Crear contacto inicial',
    'task' => 'Crear tarefa',
    'bounce' => 'Xestión de correos devoltos',
  ),
  'dom_email_distribution' => array (
    '0' => '',
    'direct' => 'Asignación directa',
    'roundRobin' => 'Asignación rotatoria',
    'leastBusy' => 'Menor ocupación',
  ),
  'dom_email_errors' => array (
    '1' => 'Seleccionar un só usuario ao Asignar elementos directamente.',
    '2' => 'Debe asignar Só os elementos marcados ao Asignar elementos directamente.',
  ),
  'dom_email_bool' => array (
    'bool_true' => 'Si',
    'bool_false' => 'Non',
  ),
  'dom_int_bool' => array (
    '1' => 'Si',
    '0' => 'Non',
  ),
  'dom_switch_bool' => array (
    'on' => 'Si',
    'off' => 'Non',
    '0' => '',
  ),
  'dom_email_link_type' => array (
    '0' => '',
    'sugar' => 'Cliente de correo do SugarCRM',
    'mailto' => 'Cliente de correo externo',
  ),
  'dom_email_editor_option' => array (
    '0' => '',
    'html' => 'Correo HTML',
    'plain' => 'Correo de texto plano',
  ),
  'schedulers_times_dom' => array (
    'not run' => 'Tempo de execución excedido, Non se executou',
    'ready' => 'Listo',
    'in progress' => 'En progreso',
    'failed' => 'Fallou',
    'completed' => 'Terminado',
    'no curl' => 'Non se executou: o cURL non está dispoñible',
  ),
  'scheduler_status_dom' => array (
    'Active' => 'Activo',
    'Inactive' => 'Inactivo',
  ),
  'scheduler_period_dom' => array (
    'min' => 'Minutos',
    'hour' => 'Horas',
  ),
  'forecast_schedule_status_dom' => array (
    'Active' => 'Activo',
    'Inactive' => 'Inactivo',
  ),
  'forecast_type_dom' => array (
    'Direct' => 'Directo',
    'Rollup' => 'Agregado',
  ),
  'document_category_dom' => array (
    '0' => '',
    'Marketing' => 'Mercadotecnia',
    'Knowledege Base' => 'Base de coñecemento',
    'Sales' => 'Vendas',
  ),
  'document_subcategory_dom' => array (
    '0' => '',
    'Marketing Collateral' => 'Mercadotecnia colateral',
    'Product Brochures' => 'Folletos de produtos',
    'FAQ' => 'Preguntas frecuentes',
  ),
  'document_status_dom' => array (
    'Active' => 'Activo',
    'Draft' => 'Borrador',
    'FAQ' => 'Preguntas frecuentes',
    'Expired' => 'Caducado',
    'Under Review' => 'Baixo revisión',
    'Pending' => 'Pendente',
  ),
  'document_template_type_dom' => array (
    '0' => '',
    'mailmerge' => 'Combinación de correspondencia',
    'eula' => 'CLUF',
    'nda' => 'NDA',
    'license' => 'Acordo de licenza',
  ),
  'dom_meeting_accept_options' => array (
    'accept' => 'Aceptar',
    'decline' => 'Rexeitar',
    'tentative' => 'Provisional',
  ),
  'dom_meeting_accept_status' => array (
    'accept' => 'Aceptar',
    'decline' => 'Rexeitar',
    'tentative' => 'Provisional',
    'none' => 'Ningún',
  ),
  'prospect_list_type_dom' => array (
    'default' => 'Predeterminado',
    'seed' => 'Preseleccionar',
    'exempt_domain' => 'Lista de supresión - Por dominio',
    'exempt_address' => 'Lista de supresión - Por enderezo de correo',
    'exempt' => 'Lista de supresión - Por Id.',
    'test' => 'Proba',
  ),
  'email_marketing_status_dom' => array (
    '0' => '',
    'active' => 'Activo',
    'inactive' => 'Inactivo',
  ),
  'campainglog_activity_type_dom' => array (
    '0' => '',
    'targeted' => 'Mensaxe enviada/tentada',
    'send error' => 'Mensaxes devoltas,Outras',
    'invalid email' => 'Mensaxes devoltas,Correo non válido',
    'link' => 'Ligazón click-through',
    'viewed' => 'Mensaxe visualizada',
    'removed' => 'Dado de baixa',
    'lead' => 'Contactos iniciais creados',
    'contact' => 'Contactos creados',
    'blocked' => 'Suprimido por enderezo ou por dominio',
  ),
  'campainglog_target_type_dom' => array (
    'Contacts' => 'Contactos',
    'Users' => 'Usuarios',
    'Prospects' => 'Obxectivos',
    'Leads' => 'Contactos iniciais',
  ),
  'merge_operators_dom' => array (
    'like' => 'Contén',
    'exact' => 'Exactamente',
    'start' => 'Comeza por',
  ),
  'custom_fields_merge_dup_dom' => array (
    '0' => 'Desactivado',
    '1' => 'Activado',
  ),
  'navigation_paradigms' => array (
    'm' => 'Módulos',
    'gm' => 'Módulos agrupados',
  ),
  'projects_priority_options' => array (
    'high' => 'Alta',
    'medium' => 'Media',
    'low' => 'Baixa',
  ),
  'projects_status_options' => array (
    'notstarted' => 'Non iniciado',
    'inprogress' => 'En progreso',
    'completed' => 'Terminado',
  ),
);

$app_strings=array(
  'ERR_CREATING_FIELDS' => 'Erro ao encher os campos de detalle adicionais:',
  'ERR_CREATING_TABLE' => 'Erro ao crear a táboa:',
  'ERR_DECIMAL_SEP_EQ_THOUSANDS_SEP' => 'O separador decimal non pode usar o mesmo carácter que o separador de millares.nn Modifique os valores.',
  'ERR_DELETE_RECORD' => 'Débese especificar un número de rexistro para eliminar o contacto.',
  'ERR_EXPORT_DISABLED' => 'As exportacións están desactivadas',
  'ERR_EXPORT_TYPE' => 'Erro ao exportar',
  'ERR_INVALID_AMOUNT' => 'Introduza un importe válido.',
  'ERR_INVALID_DATE_FORMAT' => 'O formato de data debe ser:',
  'ERR_INVALID_DATE' => 'Introduza unha data válida.',
  'ERR_INVALID_DAY' => 'Introduza un día válido.',
  'ERR_INVALID_EMAIL_ADDRESS' => 'non é un enderezo de correo válido.',
  'ERR_INVALID_FILE_REFERENCE' => 'Referencia de ficheiro non válida',
  'ERR_INVALID_HOUR' => 'Introduza unha hora válida.',
  'ERR_INVALID_MONTH' => 'Introduza un mes válido.',
  'ERR_INVALID_TIME' => 'Introduza unha hora válida.',
  'ERR_INVALID_YEAR' => 'Introduza un ano válido de catro díxitos.',
  'ERR_NEED_ACTIVE_SESSION' => 'É necesaria unha sesión activa para exportar contido.',
  'ERR_NOT_ADMIN' => 'Acceso non autorizado á administración.',
  'ERR_MISSING_REQUIRED_FIELDS' => 'Falta un campo requirido:',
  'ERR_INVALID_VALUE' => 'Valor non válido:',
  'ERR_NO_SUCH_FILE' => 'O ficheiro non existe no sistema',
  'ERR_NO_SINGLE_QUOTE' => 'Non pode usar as comiñas simples para',
  'ERR_NOTHING_SELECTED' => 'Faga unha selección antes de proceder.',
  'ERR_OPPORTUNITY_NAME_DUPE' => 'Xa existe unha oportunidade co nome %s. Introduza outro nome abaixo.',
  'ERR_OPPORTUNITY_NAME_MISSING' => 'Non se introduciu un nome de oportunidade. Introduza un nome de oportunidade abaixo.',
  'ERR_POTENTIAL_SEGFAULT' => 'Detectouse un fallo de segmentación potencial do Apache. Notifíqueo ao administrador do sistema para que confirme este problema e envíe un informe ao SugarCRM.',
  'ERR_SELF_REPORTING' => 'Un usuario non pode enviar un informe a si mesmo.',
  'ERR_SINGLE_QUOTE' => 'Este campo non soporta o uso de comiñas simples. Modifique o valor.',
  'ERR_SQS_NO_MATCH_FIELD' => 'Non hai coincidencias para o campo:',
  'ERR_SQS_NO_MATCH' => 'Non hai coincidencias',
  'LBL_ACCOUNT' => 'Conta',
  'LBL_ACCOUNTS' => 'Contas',
  'LBL_ACCUMULATED_HISTORY_BUTTON_KEY' => 'H',
  'LBL_ACCUMULATED_HISTORY_BUTTON_LABEL' => 'Visualizar o resumo',
  'LBL_ACCUMULATED_HISTORY_BUTTON_TITLE' => 'Visualizar o resumo [Alt+H]',
  'LBL_ADD_BUTTON_KEY' => 'A',
  'LBL_ADD_BUTTON_TITLE' => 'Engadir [Alt+A]',
  'LBL_ADD_BUTTON' => 'Engadir',
  'LBL_ADD_DOCUMENT' => 'Engadir documento',
  'LBL_ADD_TO_PROSPECT_LIST_BUTTON_KEY' => 'L',
  'LBL_ADD_TO_PROSPECT_LIST_BUTTON_LABEL' => 'Engadir á lista de obxectivos',
  'LBL_ADD_TO_PROSPECT_LIST_BUTTON_TITLE' => 'Engadir á lista de obxectivos',
  'LBL_ADDITIONAL_DETAILS_CLOSE_TITLE' => 'Prema para pechar',
  'LBL_ADDITIONAL_DETAILS_CLOSE' => 'Pechar',
  'LBL_ADDITIONAL_DETAILS' => 'Detalles adicionais',
  'LBL_ADMIN' => 'Administración',
  'LBL_ALT_HOT_KEY' => 'Alt+',
  'LBL_ARCHIVE' => 'Arquivo',
  'LBL_ASSIGNED_TO_USER' => 'Asignado ao usuario',
  'LBL_ASSIGNED_TO' => 'Asignado a:',
  'LBL_BACK' => 'Anterior',
  'LBL_BILL_TO_ACCOUNT' => 'Facturar na conta',
  'LBL_BILL_TO_CONTACT' => 'Facturar ao contacto',
  'LBL_BROWSER_TITLE' => 'SugarCRM - CRM comercial Open Source',
  'LBL_BUGS' => 'Incidencias',
  'LBL_BY' => 'por',
  'LBL_CALLS' => 'Chamadas',
  'LBL_CAMPAIGNS_SEND_QUEUED' => 'Enviar os correos de campaña na fila',
  'LBL_CANCEL_BUTTON_KEY' => 'X',
  'LBL_CANCEL_BUTTON_LABEL' => 'Cancelar',
  'LBL_CANCEL_BUTTON_TITLE' => 'Cancelar [Alt+X]',
  'LBL_CASE' => 'Caso',
  'LBL_CASES' => 'Casos',
  'LBL_CHANGE_BUTTON_KEY' => 'G',
  'LBL_CHANGE_BUTTON_LABEL' => 'Modificar',
  'LBL_CHANGE_BUTTON_TITLE' => 'Modificar [Alt+G]',
  'LBL_CHARSET' => 'UTF-8',
  'LBL_CHECKALL' => 'Verificar todo',
  'LBL_CLEAR_BUTTON_KEY' => 'C',
  'LBL_CLEAR_BUTTON_LABEL' => 'Limpar',
  'LBL_CLEAR_BUTTON_TITLE' => 'Limpar [Alt+C]',
  'LBL_CLEARALL' => 'Limpar todo',
  'LBL_CLOSE_WINDOW' => 'Pechar ventá',
  'LBL_CLOSEALL_BUTTON_KEY' => 'Q',
  'LBL_CLOSEALL_BUTTON_LABEL' => 'Pechar todo',
  'LBL_CLOSEALL_BUTTON_TITLE' => 'Pechar todo [Alt+I]',
  'LBL_CLOSE_AND_CREATE_BUTTON_LABEL' => 'Pechar e crear novo',
  'LBL_CLOSE_AND_CREATE_BUTTON_TITLE' => 'Pechar e crear novo [Alt+C]',
  'LBL_CLOSE_AND_CREATE_BUTTON_KEY' => 'C',
  'LBL_COMPOSE_EMAIL_BUTTON_KEY' => 'L',
  'LBL_COMPOSE_EMAIL_BUTTON_LABEL' => 'Redactar un correo',
  'LBL_COMPOSE_EMAIL_BUTTON_TITLE' => 'Redactar un correo [Alt+L]',
  'LBL_CONTACT_LIST' => 'Lista de contactos',
  'LBL_CONTACT' => 'Contacto',
  'LBL_CONTACTS' => 'Contactos',
  'LBL_CREATE_BUTTON_LABEL' => 'Crear',
  'LBL_CREATED_BY_USER' => 'Creado polo usuario',
  'LBL_CREATED' => 'Creado por',
  'LBL_CURRENT_USER_FILTER' => 'Só os meus elementos:',
  'LBL_DATE_ENTERED' => 'Data de creación:',
  'LBL_DATE_MODIFIED' => 'Última modificación:',
  'LBL_DELETE_BUTTON_KEY' => 'D',
  'LBL_DELETE_BUTTON_LABEL' => 'Eliminar',
  'LBL_DELETE_BUTTON_TITLE' => 'Eliminar [Alt+D]',
  'LBL_DELETE_BUTTON' => 'Eliminar',
  'LBL_DELETE' => 'Eliminar',
  'LBL_DELETED' => 'Eliminado',
  'LBL_DIRECT_REPORTS' => 'Informes directos',
  'LBL_DONE_BUTTON_KEY' => 'X',
  'LBL_DONE_BUTTON_LABEL' => 'Feito',
  'LBL_DONE_BUTTON_TITLE' => 'Feito [Alt+X]',
  'LBL_DST_NEEDS_FIXIN' => 'A aplicación require que se aplique un arranxo no horario de verán. Vaia á ligazón <a href="index.php?module=Administration&action=DstFix">Reparar</a> na consola de Administración e aplique o arranxo de horario de verán.',
  'LBL_DUPLICATE_BUTTON_KEY' => 'U',
  'LBL_DUPLICATE_BUTTON_LABEL' => 'Duplicar',
  'LBL_DUPLICATE_BUTTON_TITLE' => 'Duplicar [Alt+U]',
  'LBL_DUPLICATE_BUTTON' => 'Duplicar',
  'LBL_EDIT_BUTTON_KEY' => 'E',
  'LBL_EDIT_BUTTON_LABEL' => 'Editar',
  'LBL_EDIT_BUTTON_TITLE' => 'Editar [Alt+E]',
  'LBL_EDIT_BUTTON' => 'Editar',
  'LBL_VIEW_BUTTON_KEY' => 'V',
  'LBL_VIEW_BUTTON_LABEL' => 'Visualizar',
  'LBL_VIEW_BUTTON_TITLE' => 'Visualizar [Alt+V]',
  'LBL_VIEW_BUTTON' => 'Visualizar',
  'LBL_EMAIL_PDF_BUTTON_KEY' => 'M',
  'LBL_EMAIL_PDF_BUTTON_LABEL' => 'Enviar por correo como PDF',
  'LBL_EMAIL_PDF_BUTTON_TITLE' => 'Enviar por correo como PDF [Alt+M]',
  'LBL_EMAILS' => 'Correos',
  'LBL_EMPLOYEES' => 'Empregados',
  'LBL_ENTER_DATE' => 'Introducir data',
  'LBL_EXPORT_ALL' => 'Exportar todo',
  'LBL_EXPORT' => 'Exportar',
  'LBL_GO_BUTTON_LABEL' => 'Ir',
  'LBL_HIDE' => 'Ocultar',
  'LBL_ID' => 'ID',
  'LBL_IMPORT_PROSPECTS' => 'Importar obxectivos',
  'LBL_IMPORT' => 'Importar',
  'LBL_IMPORT_STARTED' => 'Importación iniciada:',
  'LBL_MISSING_CUSTOM_DELIMITER' => 'Debe especificar un delimitador personalizado.',
  'LBL_LAST_VIEWED' => 'Última visualización',
  'LBL_LEADS' => 'Contactos iniciais',
  'LBL_CAMPAIGN' => 'Campaña:',
  'LBL_CAMPAIGN_ID' => 'id de campaña',
  'LBL_LIST_ACCOUNT_NAME' => 'Nome de conta',
  'LBL_LIST_ASSIGNED_USER' => 'Usuario',
  'LBL_LIST_CONTACT_NAME' => 'Nome de contacto',
  'LBL_LIST_CONTACT_ROLE' => 'Rol de contacto',
  'LBL_LIST_EMAIL' => 'Correo',
  'LBL_LIST_NAME' => 'Nome',
  'LBL_LIST_OF' => 'de',
  'LBL_LIST_PHONE' => 'Teléfono',
  'LBL_LIST_USER_NAME' => 'Nome de usuario',
  'LBL_LISTVIEW_MASS_UPDATE_CONFIRM' => 'Está seguro de que quere actualizar toda a lista?',
  'LBL_LISTVIEW_NO_SELECTED' => 'Seleccione polo menos 1 rexistro para proceder.',
  'LBL_LISTVIEW_TWO_REQUIRED' => 'Seleccione polo menos 2 rexistros para proceder.',
  'LBL_LISTVIEW_OPTION_CURRENT' => 'Páxina actual',
  'LBL_LISTVIEW_OPTION_ENTIRE' => 'Toda a lista',
  'LBL_LISTVIEW_OPTION_SELECTED' => 'Rexistros seleccionados',
  'LBL_LISTVIEW_SELECTED_OBJECTS' => 'Seleccionados:',
  'LBL_LOCALE_NAME_EXAMPLE_FIRST' => 'John',
  'LBL_LOCALE_NAME_EXAMPLE_LAST' => 'Doe',
  'LBL_LOCALE_NAME_EXAMPLE_SALUTATION' => 'Sr.',
  'LBL_LOGOUT' => 'Terminar a sesión',
  'LBL_MAILMERGE_KEY' => 'M',
  'LBL_MAILMERGE' => 'Combinación de correspondencia',
  'LBL_MASS_UPDATE' => 'Actualización masiva',
  'LBL_MEETINGS' => 'Reunións',
  'LBL_MEMBERS' => 'Integrantes',
  'LBL_MODIFIED_BY_USER' => 'Modificado polo usuario',
  'LBL_MODIFIED' => 'Modificado por',
  'LBL_MY_ACCOUNT' => 'A miña conta',
  'LBL_NAME' => 'Nome',
  'LBL_NEW_BUTTON_KEY' => 'N',
  'LBL_NEW_BUTTON_LABEL' => 'Crear',
  'LBL_NEW_BUTTON_TITLE' => 'Crear [Alt+N]',
  'LBL_NEXT_BUTTON_LABEL' => 'Seguinte',
  'LBL_NONE' => '--Ningún--',
  'LBL_NOTES' => 'Notas',
  'LBL_OPENALL_BUTTON_KEY' => 'O',
  'LBL_OPENALL_BUTTON_LABEL' => 'Abrir todo',
  'LBL_OPENALL_BUTTON_TITLE' => 'Abrir todo [Alt+O]',
  'LBL_OPENTO_BUTTON_KEY' => 'T',
  'LBL_OPENTO_BUTTON_LABEL' => 'Abrir en:',
  'LBL_OPENTO_BUTTON_TITLE' => 'Abrir en: [Alt+T]',
  'LBL_OPPORTUNITIES' => 'Oportunidades',
  'LBL_OPPORTUNITY_NAME' => 'Nome de oportunidade',
  'LBL_OPPORTUNITY' => 'Oportunidade',
  'LBL_OR' => 'OU',
  'LBL_PERCENTAGE_SYMBOL' => '%',
  'LBL_PRODUCT_BUNDLES' => 'Grupos de produtos',
  'LBL_PRODUCTS' => 'Produtos',
  'LBL_PROJECT_TASKS' => 'Tarefas de proxecto',
  'LBL_PROJECTS' => 'Proxectos',
  'LBL_QUOTE_TO_OPPORTUNITY_KEY' => 'O',
  'LBL_QUOTE_TO_OPPORTUNITY_LABEL' => 'Crear unha oportunidade a partir dun orzamento',
  'LBL_QUOTE_TO_OPPORTUNITY_TITLE' => 'Crear unha oportunidade a partir dun orzamento [Alt+O]',
  'LBL_QUOTES_SHIP_TO' => 'Enviar orzamentos a',
  'LBL_QUOTES' => 'Orzamentos',
  'LBL_RELATED_RECORDS' => 'Rexistros relacionados',
  'LBL_REMOVE' => 'Eliminar',
  'LBL_REQUIRED_SYMBOL' => '*',
  'LBL_SAVE_BUTTON_KEY' => 'S',
  'LBL_SAVE_BUTTON_LABEL' => 'Gardar',
  'LBL_SAVE_BUTTON_TITLE' => 'Gardar [Alt+S]',
  'LBL_SAVE_AS_BUTTON_KEY' => 'A',
  'LBL_SAVE_AS_BUTTON_LABEL' => 'Gardar como',
  'LBL_SAVE_AS_BUTTON_TITLE' => 'Gardar como [Alt+A]',
  'LBL_FULL_FORM_BUTTON_KEY' => 'F',
  'LBL_FULL_FORM_BUTTON_LABEL' => 'Formulario completo',
  'LBL_FULL_FORM_BUTTON_TITLE' => 'Formulario completo [Alt+F]',
  'LBL_SAVE_NEW_BUTTON_KEY' => 'V',
  'LBL_SAVE_NEW_BUTTON_LABEL' => 'Gardar e crear novo',
  'LBL_SAVE_NEW_BUTTON_TITLE' => 'Gardar e crear novo [Alt+V]',
  'LBL_SEARCH_BUTTON_KEY' => 'Q',
  'LBL_SEARCH_BUTTON_LABEL' => 'Buscar',
  'LBL_SEARCH_BUTTON_TITLE' => 'Buscar [Alt+Q]',
  'LBL_SEARCH' => 'Buscar',
  'LBL_SELECT_BUTTON_KEY' => 'T',
  'LBL_SELECT_BUTTON_LABEL' => 'Seleccionar',
  'LBL_SELECT_BUTTON_TITLE' => 'Seleccionar [Alt+T]',
  'LBL_SELECT_CONTACT_BUTTON_KEY' => 'T',
  'LBL_SELECT_CONTACT_BUTTON_LABEL' => 'Seleccionar contacto',
  'LBL_SELECT_CONTACT_BUTTON_TITLE' => 'Seleccionar contacto [Alt+T]',
  'LBL_GRID_SELECTED_FILE' => 'ficheiro seleccionado',
  'LBL_GRID_SELECTED_FILES' => 'ficheiros seleccionados',
  'LBL_SELECT_REPORTS_BUTTON_LABEL' => 'Seleccionar desde informes',
  'LBL_SELECT_REPORTS_BUTTON_TITLE' => 'Seleccionar informes',
  'LBL_SELECT_USER_BUTTON_KEY' => 'U',
  'LBL_SELECT_USER_BUTTON_LABEL' => 'Seleccionar usuario',
  'LBL_SELECT_USER_BUTTON_TITLE' => 'Seleccionar usuario [Alt+U]',
  'LBL_SERVER_RESPONSE_RESOURCES' => 'Recursos usados para construír esta páxina (consultas,ficheiros)',
  'LBL_SERVER_RESPONSE_TIME_SECONDS' => 'segundos.',
  'LBL_SERVER_RESPONSE_TIME' => 'Tempo de resposta do servidor:',
  'LBL_SHIP_TO_ACCOUNT' => 'Enviar á conta',
  'LBL_SHIP_TO_CONTACT' => 'Enviar ao contacto',
  'LBL_SHORTCUTS' => 'Atallos',
  'LBL_SHOW' => 'Mostrar',
  'LBL_SQS_INDICATOR' => '',
  'LBL_STATUS_UPDATED' => 'Actualizouse o estado para este evento!',
  'LBL_STATUS' => 'Estado:',
  'LBL_SUBJECT' => 'Asunto:',
  'LBL_SYNC' => 'Sincronizar',
  'LBL_TABGROUP_ALL' => 'Todo',
  'LBL_TABGROUP_ACTIVITIES' => 'Actividades',
  'LBL_TABGROUP_COLLABORATION' => 'Colaboración',
  'LBL_TABGROUP_HOME' => 'Inicio',
  'LBL_TABGROUP_MARKETING' => 'Mercadotecnia',
  'LBL_TABGROUP_MY_PORTALS' => 'Os meus portais',
  'LBL_TABGROUP_OTHER' => 'Outro',
  'LBL_TABGROUP_REPORTS' => 'Informes',
  'LBL_TABGROUP_SALES' => 'Vendas',
  'LBL_TABGROUP_SUPPORT' => 'Soporte',
  'LBL_TABGROUP_TOOLS' => 'Ferramentas',
  'LBL_TASKS' => 'Tarefas',
  'LBL_TEAMS_LINK' => 'Equipo',
  'LBL_THOUSANDS_SYMBOL' => 'K',
  'LBL_TRACK_EMAIL_BUTTON_KEY' => 'K',
  'LBL_TRACK_EMAIL_BUTTON_LABEL' => 'Arquivar correo',
  'LBL_TRACK_EMAIL_BUTTON_TITLE' => 'Arquivar correo [Alt+K]',
  'LBL_UNAUTH_ADMIN' => 'Acceso non autorizado á administración',
  'LBL_UNDELETE_BUTTON_LABEL' => 'Recuperar',
  'LBL_UNDELETE_BUTTON_TITLE' => 'Recuperar [Alt+D]',
  'LBL_UNDELETE_BUTTON' => 'Recuperar',
  'LBL_UNDELETE' => 'Recuperar',
  'LBL_UNSYNC' => 'Desincronizar',
  'LBL_UPDATE' => 'Actualizar',
  'LBL_USER_LIST' => 'Lista de usuario',
  'LBL_USERS_SYNC' => 'Sincronización de usuarios',
  'LBL_USERS' => 'Usuarios',
  'LBL_VIEW_PDF_BUTTON_KEY' => 'P',
  'LBL_VIEW_PDF_BUTTON_LABEL' => 'Imprimir como PDF',
  'LBL_VIEW_PDF_BUTTON_TITLE' => 'Imprimir como PDF [Alt+P]',
  'LNK_ABOUT' => 'Sobre',
  'LNK_ADVANCED_SEARCH' => 'Busca avanzada',
  'LNK_BASIC_SEARCH' => 'Busca básica',
  'LNK_SAVED_VIEWS' => 'Busca gardada e Disposición',
  'LNK_DELETE_ALL' => 'eliminar todo',
  'LNK_DELETE' => 'eliminar',
  'LNK_EDIT' => 'editar',
  'LNK_GET_LATEST' => 'Obter o último',
  'LNK_GET_LATEST_TOOLTIP' => 'Substituír coa última versión',
  'LNK_HELP' => 'Axuda',
  'LNK_LIST_END' => 'Fin',
  'LNK_LIST_NEXT' => 'Seguinte',
  'LNK_LIST_PREVIOUS' => 'Anterior',
  'LNK_LIST_RETURN' => 'Volver',
  'LNK_LIST_START' => 'Comezar',
  'LNK_LOAD_SIGNED' => 'Asinado',
  'LNK_LOAD_SIGNED_TOOLTIP' => 'Substituír cun documento asinado',
  'LNK_PRINT' => 'Imprimir',
  'LNK_REMOVE' => 'eliminar',
  'LNK_RESUME' => 'Continuar',
  'LNK_VIEW_CHANGE_LOG' => 'Ver o rexistro de modificacións',
  'NTC_CLICK_BACK' => 'Prema o botón Atrás do navegador e corrixa o erro.',
  'NTC_DATE_FORMAT' => '(aaaa-mm-dd)',
  'NTC_DATE_TIME_FORMAT' => '(aaaa-mm-dd 24:00)',
  'NTC_DELETE_CONFIRMATION_MULTIPLE' => 'Está seguro de que quere eliminar o(s) rexistro(s) seleccionado(s)?',
  'NTC_DELETE_CONFIRMATION' => 'Está seguro de que quere eliminar este rexistro?',
  'NTC_LOGIN_MESSAGE' => 'Introduza o seu nome de usuario e contrasinal.',
  'NTC_NO_ITEMS_DISPLAY' => 'ningún',
  'NTC_REMOVE_CONFIRMATION' => 'Está seguro de que quere eliminar esta relación?',
  'NTC_REQUIRED' => 'Indica un campo requirido',
  'NTC_SUPPORT_SUGARCRM' => 'Soporte o proxecto Open Source SugarCRM cunha doazón a través do PayPal - é rápido, gratis e seguro!',
  'NTC_TIME_FORMAT' => '(24:00)',
  'NTC_WELCOME' => 'Benvido',
  'NTC_YEAR_FORMAT' => '(aaaa)',
  'LOGIN_LOGO_ERROR' => 'Substitúa os logotipos do SugarCRM.',
  'ERROR_FULLY_EXPIRED' => 'A licenza da súa empresa para o SugarCRM expirou vai máis de 30 días e é necesario actualizala. Só os administradores poderán iniciar a sesión.',
  'ERROR_LICENSE_EXPIRED' => 'É necesario actualizar a licenza da súa empresa para o SugarCRM. Só os administradores poderán iniciar a sesión',
  'ERROR_LICENSE_VALIDATION' => 'É necesario validar a licenza da súa empresa para o SugarCRM. Só os administradores poderán iniciar a sesión',
  'ERROR_NO_RECORD' => 'Houbo un erro ao recuperar o rexistro. Pode que este rexistro se eliminase ou que non estea autorizado a velo.',
  'LBL_DUP_MERGE' => 'Encontrar duplicados',
  'LBL_MANAGE_SUBSCRIPTIONS' => 'Xestionar subscricións',
  'LBL_MANAGE_SUBSCRIPTIONS_FOR' => 'Xestionar subscricións para',
  'LBL_SUBSCRIBE' => 'Subscribirse',
  'LBL_UNSUBSCRIBE' => 'Desubscribirse',
  'LBL_LOADING' => 'Cargando...',
  'LBL_SAVING_LAYOUT' => 'Gardando a disposición...',
  'LBL_SAVED_LAYOUT' => 'Gardouse a disposición.',
  'LBL_SAVED' => 'Gardado',
  'LBL_SAVING' => 'Gardando',
  'LBL_FAILED' => 'Fallou!',
  'LBL_DISPLAY_COLUMNS' => 'Mostrar columnas',
  'LBL_HIDE_COLUMNS' => 'Ocultar columnas',
  'LBL_SEARCH_CRITERIA' => 'Criterios de busca',
  'LBL_SAVED_VIEWS' => 'Visualizacións gardadas',
  'LBL_PROCESSING_REQUEST' => 'Procesando...',
  'LBL_REQUEST_PROCESSED' => 'Feito',
  'LBL_MERGE_DUPLICATES' => 'Combinar duplicados',
  'LBL_SAVED_SEARCH_SHORTCUT' => 'Buscas gardadas',
  'LBL_SEARCH_POPULATE_ONLY' => 'Efectuar unha busca usando o formulario de busca arriba',
  'LBL_DETAILVIEW' => 'Visualización detallada',
  'LBL_LISTVIEW' => 'Visualización en lista',
  'LBL_EDITVIEW' => 'Visualización de edición',
  'LBL_SEARCHFORM' => 'Formulario de busca',
  'LBL_SAVED_SEARCH_ERROR' => 'Proporcione un nome para esta visualización.',
  'LBL_DISPLAY_LOG' => 'Visualizar o rexistro',
  'ERROR_JS_ALERT_SYSTEM_CLASS' => 'Sistema',
  'ERROR_JS_ALERT_TIMEOUT_TITLE' => 'Tempo de espera da sesión',
  'ERROR_JS_ALERT_TIMEOUT_MSG_1' => 'A súa sesión excederá o tempo de espera en 2 minutos. Garde o seu traballo.',
  'ERROR_JS_ALERT_TIMEOUT_MSG_2' => 'A súa sesión excedeu o tempo de espera.',
  'MSG_JS_ALERT_MTG_REMINDER_AGENDA' => 'Axenda:',
  'MSG_JS_ALERT_MTG_REMINDER_MEETING' => 'Reunión',
  'MSG_JS_ALERT_MTG_REMINDER_CALL' => 'Chamada',
  'MSG_JS_ALERT_MTG_REMINDER_TIME' => 'Hora:',
  'MSG_JS_ALERT_MTG_REMINDER_LOC' => 'Lugar:',
  'MSG_JS_ALERT_MTG_REMINDER_DESC' => 'Descrición:',
  'MSG_JS_ALERT_MTG_REMINDER_MSG' => 'Prema en OK para visualizar esta reunión ou prema en Cancelar para descartar esta mensaxe.',
  'LBL_ADD_TO_FAVORITES' => 'Engadir aos meus favoritos',
  'LBL_CREATE_CONTACT' => 'Crear contacto',
  'LBL_CREATE_CASE' => 'Crear caso',
  'LBL_CREATE_NOTE' => 'Crear nota',
  'LBL_CREATE_OPPORTUNITY' => 'Crear oportunidade',
  'LBL_SCHEDULE_CALL' => 'Programar chamada',
  'LBL_SCHEDULE_MEETING' => 'Programar reunión',
  'LBL_CREATE_TASK' => 'Crear tarefa',
  'LBL_REMOVE_FROM_FAVORITES' => 'Eliminar dos meus favoritos',
  'LBL_GENERATE_WEB_TO_LEAD_FORM' => 'Xerar formulario',
  'LBL_SAVE_WEB_TO_LEAD_FORM' => 'Gardar o formulario de contacto',
  'LBL_PLEASE_SELECT' => 'Seleccione',
  'LBL_REDIRECT_URL' => 'Redireccionar URL',
  'LBL_RELATED_CAMPAIGN' => 'Campaña relacionada',
  'LBL_ADD_ALL_LEAD_FIELDS' => 'Engadir todos os campos',
  'LBL_REMOVE_ALL_LEAD_FIELDS' => 'Eliminar todos os campos',
  'LBL_ONLY_IMAGE_ATTACHMENT' => 'Só se pode incorporar un anexo do tipo imaxe',
  'LBL_TRAINING' => 'Formación',
  'ERR_DATABASE_CONN_DROPPED' => 'Erro ao executar unha consulta. É posible que a súa base de datos fixese caer a conexión. Actualice esta páxina, pode que sexa necesario reiniciar o servidor Web.',
  'ERR_MSSQL_DB_CONTEXT' => 'Modificouse o contexto da base de datos como',
);#Hai 903 entradas neste ficheiro de galego

?>
